In [0]:
import numpy as np

In [0]:
# Python program to implement a weights by perceptron learning method for FFNN with non-linear units

train_inputs = np.transpose(np.array([[-1, 0, 0, 0, 0, 1], [-1, 0, 0, 0, 1, 0], [-1, 0, 0, 1, 0, 0], [-1, 0, 1, 0, 0, 0],[-1, 1, 0, 0, 0, 0]]))

print ("\nTraining Input ->") 
print (train_inputs)
#Output is based on (place of 1)%2

train_outputs = np.array([[1,0,1,0,1]])
Rows_in_train_inputs = len(train_inputs)
#print (Rows_in_train_inputs)
Rows_in_train_outputs = len(train_outputs)
#print (Rows_in_train_outputs)
np.random.seed(1)

Computation_weights = np.transpose(np.random.rand(Rows_in_train_inputs,1))
#print (len(Computation_weights))
print ('\nRandom weights at the start of training') 
print (Computation_weights)

print ("\nTraining Output ->") 
print (train_outputs)
print("\nGiving Input and Output Pair one by one")

learning_rate = 0.99
print("Learning_rate:\n",learning_rate)

for i in range (len(train_inputs[0])):
  train_inputs_i = train_inputs[:,i]
  train_inputs_i = np.reshape(train_inputs_i,(Rows_in_train_inputs,1))
  #print(np.shape(train_inputs_i))
  train_outputs_i = [train_outputs[:,i]]
  train_outputs_i = np.reshape(train_outputs_i,(Rows_in_train_outputs,1))
  #print(np.shape(train_outputs_i))
  Wta = np.matmul((Computation_weights),train_inputs_i)
  #print("\n",Wta)
  if(train_outputs_i[0][0]==1 and Wta[0][0]<=0):
    weight_new = learning_rate*train_inputs_i
    print ('\nWeights after training',i,"th iteration") 
    Computation_weights = Computation_weights + np.transpose(weight_new)
  elif(train_outputs_i[0][0]==1 and Wta[0][0]>0):
    weight_new = learning_rate*train_inputs_i
    print ('\nWeights after training',i,"th iteration") 
    Computation_weights = Computation_weights
  elif(train_outputs_i[0][0]==0 and Wta[0][0]>0):
    weight_new = learning_rate*train_inputs_i
    print ('\nWeights after training',i,"th iteration") 
    Computation_weights = Computation_weights - np.transpose(weight_new)
  elif(train_outputs_i[0][0]==0 and Wta[0][0]<=0):
    weight_new = learning_rate*train_inputs_i
    print ('\nWeights after training',i,"th iteration") 
    Computation_weights = Computation_weights
  print (Computation_weights)

print ('\nNew weights after training') 
print (Computation_weights)
#print (np.shape(Computation_weights))
# Test the neural network with a new situation. 

print ("\nTesting network ->") 
test_matrix = np.array([[-1],[1],[0],[0],[0],[0]])

print("\nOutput Y_hat")
#print (np.shape(train_inputs))
Y_hat = np.matmul((Computation_weights), train_inputs)
print(Y_hat)

print("\nSigmoid of Y_hat")
sigmoid = 1 / (1 + np.exp(-Y_hat))
print(sigmoid)

print("\nError")
print(np.linalg.norm(train_outputs-sigmoid))

print ("\nTest Input ->") 
print (test_matrix)
output = np.matmul((Computation_weights), test_matrix)

print ("\nTest Output ->") 
print(1 / (1 + np.exp(-output[0][0])))


Training Input ->
[[-1 -1 -1 -1 -1]
 [ 0  0  0  0  1]
 [ 0  0  0  1  0]
 [ 0  0  1  0  0]
 [ 0  1  0  0  0]
 [ 1  0  0  0  0]]

Random weights at the start of training
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02]]

Training Output ->
[[1 0 1 0 1]]

Giving Input and Output Pair one by one
Learning_rate:
 0.99

Weights after training 0 th iteration
[[-5.72977995e-01  7.20324493e-01  1.14374817e-04  3.02332573e-01
   1.46755891e-01  1.08233859e+00]]

Weights after training 1 th iteration
[[ 4.17022005e-01  7.20324493e-01  1.14374817e-04  3.02332573e-01
  -8.43244109e-01  1.08233859e+00]]

Weights after training 2 th iteration
[[-5.72977995e-01  7.20324493e-01  1.14374817e-04  1.29233257e+00
  -8.43244109e-01  1.08233859e+00]]

Weights after training 3 th iteration
[[ 0.417022    0.72032449 -0.98988563  1.29233257 -0.84324411  1.08233859]]

Weights after training 4 th iteration
[[ 0.417022    0.72032449 -0.98988563  1.29233257 -0.84324411 

In [0]:
# Python program to implement a weights by perceptron gradient descent learning method for FFNN with non-linear units

train_inputs = np.transpose(np.array([[-1, 0, 0, 0, 0, 1], [-1, 0, 0, 0, 1, 0], [-1, 0, 0, 1, 0, 0], [-1, 0, 1, 0, 0, 0],[-1, 1, 0, 0, 0, 0]]))

print ("\nTraining Input ->") 
print (train_inputs)
#Output is based on (place of 1)%2

train_outputs = np.array([[1,0,1,0,1]])
Rows_in_train_inputs = len(train_inputs)
#print (Rows_in_train_inputs)
Rows_in_train_outputs = len(train_outputs)
#print (Rows_in_train_outputs)
np.random.seed(1)

Computation_weights = np.transpose(np.random.rand(Rows_in_train_inputs,1))
#print (len(Computation_weights))
print ('\nRandom weights at the start of training') 
print (Computation_weights)

print ("\nTraining Output ->") 
print (train_outputs)
print("\nGiving Input and Output Pair one by one")

learning_rate = 0.41
print("Learning_rate:\n",learning_rate)

for i in range (len(train_inputs[0])):
  train_inputs_i = train_inputs[:,i]
  train_inputs_i = np.reshape(train_inputs_i,(Rows_in_train_inputs,1))
  #print(np.shape(train_inputs_i))
  train_outputs_i = [train_outputs[:,i]]
  train_outputs_i = np.reshape(train_outputs_i,(Rows_in_train_outputs,1))
  #print(np.shape(train_outputs_i))
  Wta = np.matmul((Computation_weights),train_inputs_i)
  if(Wta > 0):
    sm = 1
  else:
    sm = 0
  #print("\n",Wta)
  weight_new = learning_rate*(train_outputs_i[0][0]-sm)*train_inputs_i
  print ('\nWeights after training',i,"th iteration") 
  Computation_weights = Computation_weights + np.transpose(weight_new)
  print (Computation_weights)

print ('\nNew weights after training') 
print (Computation_weights)
#print (np.shape(Computation_weights))

# Test the neural network with a new situation. 
print ("\nTesting network ->") 
test_matrix = np.array([[-1],[1],[0],[0],[0],[0]])

print("\nOutput Y_hat")
#print (np.shape(train_inputs))
Y_hat = np.matmul((Computation_weights), train_inputs)
print(Y_hat)

print("\nSigmoid of Y_hat")
sigmoid = 1 / (1 + np.exp(-Y_hat))
print(sigmoid)

print("\nError")
print(np.linalg.norm(train_outputs-Y_hat))

print ("\nTest Input ->") 
print (test_matrix)
output = np.matmul((Computation_weights), test_matrix)

print ("\nTest Output ->") 
print(1 / (1 + np.exp(-output[0][0])))


Training Input ->
[[-1 -1 -1 -1 -1]
 [ 0  0  0  0  1]
 [ 0  0  0  1  0]
 [ 0  0  1  0  0]
 [ 0  1  0  0  0]
 [ 1  0  0  0  0]]

Random weights at the start of training
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02]]

Training Output ->
[[1 0 1 0 1]]

Giving Input and Output Pair one by one
Learning_rate:
 0.41

Weights after training 0 th iteration
[[7.02200470e-03 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 5.02338595e-01]]

Weights after training 1 th iteration
[[ 4.17022005e-01  7.20324493e-01  1.14374817e-04  3.02332573e-01
  -2.63244109e-01  5.02338595e-01]]

Weights after training 2 th iteration
[[ 7.02200470e-03  7.20324493e-01  1.14374817e-04  7.12332573e-01
  -2.63244109e-01  5.02338595e-01]]

Weights after training 3 th iteration
[[ 7.02200470e-03  7.20324493e-01  1.14374817e-04  7.12332573e-01
  -2.63244109e-01  5.02338595e-01]]

Weights after training 4 th iteration
[[ 7.02200470e-03  7.20324493e-01  1.14374