In [0]:
# import all necessery libraries 
import numpy as np

# Python program to implement a weights by computation method for FFNN with linear units 

train_inputs = np.transpose(np.array([[0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 1, 0, 0, 0],[1, 0, 0, 0, 0]]))

print ("\nTraining Input ->") 
print (train_inputs)
train_outputs = np.array([[5,0,5,0,5]])

print ("\nTraining Output ->") 
print (train_outputs)
Rows_in_train_inputs = len(train_inputs)
#print (Rows_in_train_inputs)
Rows_in_train_outputs = len(train_outputs)
#print (Rows_in_train_outputs)
np.random.seed(1)

Computation_weights = np.transpose(np.random.rand(Rows_in_train_inputs, Rows_in_train_outputs))
#print (len(Computation_weights))
print ('\nRandom weights at the start of training') 
print (Computation_weights)

print ('\nNew weights after training') 
Computation_weights = np.matmul(train_outputs, np.linalg.pinv(train_inputs))
print (Computation_weights)

# Test the neural network with a new situation. 
print ("\nTesting network ->") 
test_matrix = np.array([[1],[0],[0],[0],[0]])

print("\nOutput Y_hat")
Y_hat = np.matmul(Computation_weights, train_inputs)
print(Y_hat)

print("\nError")
print(np.linalg.norm(train_outputs-Y_hat))

print ("\nTest Input ->") 
print (test_matrix)
output = np.matmul(Computation_weights, test_matrix)

print ("\nTest Output ->") 
print(output[0][0])



Training Input ->
[[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]

Training Output ->
[[5 0 5 0 5]]

Random weights at the start of training
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01]]

New weights after training
[[5. 0. 5. 0. 5.]]

Testing network ->

Output Y_hat
[[5. 0. 5. 0. 5.]]

Error
0.0

Test Input ->
[[1]
 [0]
 [0]
 [0]
 [0]]

Test Output ->
5.0


In [0]:
# Python program to implement a weights by Hebbian learning method for FFNN with linear units

train_inputs = np.transpose(np.array([[0, 0, 0, 0, 0, 1], [0,0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0],[0, 1, 0, 0, 0, 0]]))

print ("\nTraining Input ->") 
print (train_inputs)
#Output is based on (place of 1)%2
train_outputs = np.array([[5,0,5,0,5]])
Rows_in_train_inputs = len(train_inputs)

#print (Rows_in_train_inputs)
Rows_in_train_outputs = len(train_outputs)
#print (Rows_in_train_outputs)
np.random.seed(1)

Computation_weights = np.transpose(np.random.rand(Rows_in_train_inputs, Rows_in_train_outputs))
#print (len(Computation_weights))
print ('\nRandom weights at the start of training') 
print (Computation_weights)

print ("\nTraining Output ->") 
print (train_outputs)
print("\nGiving Input and Output Pair one by one")

for i in range (len(train_inputs[0])):
  train_inputs_i = train_inputs[:,i]
  train_inputs_i = np.reshape(train_inputs_i,(Rows_in_train_inputs,1))
  #print(np.shape(train_inputs_i))
  train_outputs_i = [train_outputs[:,i]]
  train_outputs_i = np.reshape(train_outputs_i,(Rows_in_train_outputs,1))
  #print(np.shape(train_outputs_i))
  weight_new = np.matmul(train_outputs_i,np.transpose(train_inputs_i))
  print ('\nWeights after training',i,"th iteration") 
  Computation_weights = Computation_weights + weight_new
  print (Computation_weights)

print ('\nNew weights after training') 
print (Computation_weights)

# Test the neural network with a new situation. 
print ("\nTesting network ->") 
test_matrix = np.array([[0],[1],[0],[0],[0],[0]])

print("\nOutput Y_hat")
Y_hat = np.matmul(Computation_weights, train_inputs)
print(Y_hat)

print("\nError")
print(np.linalg.norm(train_outputs-Y_hat))

print ("\nTest Input ->") 
print (test_matrix)
output = np.matmul(Computation_weights, test_matrix)

print ("\nTest Output ->") 
print(output[0][0])


Training Input ->
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]

Random weights at the start of training
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02]]

Training Output ->
[[5 0 5 0 5]]

Giving Input and Output Pair one by one

Weights after training 0 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 5.09233859e+00]]

Weights after training 1 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 5.09233859e+00]]

Weights after training 2 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 5.30233257e+00
  1.46755891e-01 5.09233859e+00]]

Weights after training 3 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 5.30233257e+00
  1.46755891e-01 5.09233859e+00]]

Weights after training 4 th iteration
[[4.17022005e-01 5.72032449e+00 1.14374817e-04 5.30233257e+00
  1.46755891e-01 5.09233859e+00]]

New weights af

In [0]:
# Python program to implement a weights by Widrow's learning method for FFNN with linear units

train_inputs = np.transpose(np.array([[0, 0, 0, 0, 0, 1], [0,0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0],[0, 1, 0, 0, 0, 0]]))

print ("\nTraining Input ->") 
print (train_inputs)
#Output is based on (place of 1)%2
train_outputs = np.array([[5,0,5,0,5]])
Rows_in_train_inputs = len(train_inputs)

#print (Rows_in_train_inputs)
Rows_in_train_outputs = len(train_outputs)
#print (Rows_in_train_outputs)
np.random.seed(1)

Computation_weights = np.transpose(np.random.rand(Rows_in_train_inputs, Rows_in_train_outputs))
#print (len(Computation_weights))
print ('\nRandom weights at the start of training') 
print (Computation_weights)

print ("\nTraining Output ->") 
print (train_outputs)
print("\nGiving Input and Output Pair one by one")

learning_rate = 0.99
print("Learning_rate:\n",learning_rate)

for i in range (len(train_inputs[0])):
  train_inputs_i = train_inputs[:,i]
  train_inputs_i = np.reshape(train_inputs_i,(Rows_in_train_inputs,1))
  #print(np.shape(train_inputs_i))
  train_outputs_i = [train_outputs[:,i]]
  train_outputs_i = np.reshape(train_outputs_i,(Rows_in_train_outputs,1))
  #print(np.shape(train_outputs_i))
  weight_new = learning_rate*np.matmul((train_outputs_i-np.matmul(Computation_weights,train_inputs_i)),np.transpose(train_inputs_i))
  print ('\nWeights after training',i,"th iteration") 
  Computation_weights = Computation_weights + weight_new
  print (Computation_weights)

print ('\nNew weights after training') 
print (Computation_weights)

# Test the neural network with a new situation. 
print ("\nTesting network ->") 
test_matrix = np.array([[0],[1],[0],[0],[0],[0]])

print("\nOutput Y_hat")
Y_hat = np.matmul(Computation_weights, train_inputs)
print(Y_hat)

print("\nError")
print(np.linalg.norm(train_outputs-Y_hat))

print ("\nTest Input ->") 
print (test_matrix)
output = np.matmul(Computation_weights, test_matrix)

print ("\nTest Output ->") 
print(output[0][0])


Training Input ->
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]

Random weights at the start of training
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02]]

Training Output ->
[[5 0 5 0 5]]

Giving Input and Output Pair one by one
Learning_rate:
 0.99

Weights after training 0 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 4.95092339e+00]]

Weights after training 1 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-03 4.95092339e+00]]

Weights after training 2 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 4.95302333e+00
  1.46755891e-03 4.95092339e+00]]

Weights after training 3 th iteration
[[4.17022005e-01 7.20324493e-01 1.14374817e-06 4.95302333e+00
  1.46755891e-03 4.95092339e+00]]

Weights after training 4 th iteration
[[4.17022005e-01 4.95720324e+00 1.14374817e-06 4.95302333e+00
  1.46755891e-03 4.95092339e